app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware'=>['guest','web']], function(){
	Route::get('/', ['as'=>'login', function(){ return view('user.login');}]);
	Route::group(['namespace'=>'User'], function(){
		Route::post('/', ['as'=>'login.post', 'uses' => 'UserController@login']);
		Route::post('/register', ['as'=>'register.post', 'uses' => 'UserController@registerStore']);
		Route::get('/logout', ['as'=>'logout', 'uses' => 'UserController@logout']);
	});
	// Route::get('/forgotpassword', ['as'=>'forgotpassword', function(){ return view('user.forgotpassword.index'); } ]);
	// Route::post('/forgotpassword', ['as'=>'forgotpassword.post', 'uses' => 'UserController@forgotpassword']);
});

Route::group(['middleware'=>['web','auth']], function(){
	Route::group(['namespace'=>'User'], function(){
		Route::group(['prefix'=>'message','as' => 'message.'], function(){
			Route::get('/', ['as'=>'index', 'uses' => 'MessageController@index']);
			Route::post('/newchat', ['as' => 'newchat', 'uses' => 'MessageController@newChat']);
			Route::get('/load', ['as' => 'load', 'uses' => 'MessageController@load']);
			Route::get('/loadnew', ['as' => 'loadnew', 'uses' => 'MessageController@loadnew']);
			Route::post('/reply', ['as' => 'reply', 'uses' => 'MessageController@reply']);
			Route::get('/chatroom', ['as' => 'chatroom', 'uses' => 'MessageController@chatroom']);
		});
	});
});

resources/views/layouts/_partials/alert.blade.php
@if(session('msg-class'))
    <div class="m-alert m-alert--icon m-alert--air alert {{ session('msg-class') }} alert-dismissible fade show" role="alert">
        <div class="m-alert__icon">
            <i class="la la-warning"></i>
        </div>
        <div class="m-alert__text">
            @foreach( session('msg') as $msg)
                <span> {{ $msg }} </span><br/>
            @endforeach
        </div>
        <div class="m-alert__close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            </button>
        </div>
    </div>
@endif

resources/views/layouts/_partials/footer.blade.php
<footer class="m-grid__item m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
                <span class="m-footer__copyright">
                    {{date('Y')}} &copy; {{env('APP_NAME')}}
                </span>
            </div>
            <div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                <ul class="m-footer__nav m-nav m-nav--inline m--pull-right">
<!-- {{--                     <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">About</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Privacy</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">T&C</span>
                        </a>
                    </li>
                    <li class="m-nav__item m-nav__item">
                        <a href="#" class="m-nav__link" data-toggle="m-tooltip" title="Support Center" data-placement="left">
                            <i class="m-nav__link-icon flaticon-info m--icon-font-size-lg3"></i>
                        </a>
                    </li> --}} -->
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/_partials/head.blade.php
<head>
    <meta charset="utf-8" />
    <title>@yield('title') | {{env('APP_NAME')}}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    @include('layouts._partials.style')
    {{-- <link rel="shortcut icon" href="/metronic/assets/demo/default/media/img/logo/favicon.ico" /> --}}
</head>

resources/views/layouts/_partials/script.blade.php
<script src="/metronic_v5.1.1/metronic_v5.1.1/default/dist/default/assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
<script src="/metronic_v5.1.1/metronic_v5.1.1/default/dist/default/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>

@yield('page_script')
@yield('init_script')

resources/views/layouts/_partials/sidebar.blade.php
<button class="m-aside-left-close  m-aside-left-close--skin-light" id="m_aside_left_close_btn">
	<i class="la la-close"></i>
</button>
<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-light ">
	<div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-light m-aside-menu--submenu-skin-light " m-menu-vertical="1" m-menu-scrollable="1" m-menu-dropdown-timeout="500" style="position: relative;">
		<ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
			{{--  <li class="m-menu__section ">
				<h4 class="m-menu__section-text">Components</h4>
				<i class="m-menu__section-icon flaticon-more-v2"></i>
			</li>  --}}
			<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" m-menu-submenu-toggle="hover">
				<a href="{{route('message.index')}}" class="m-menu__link m-menu__toggle">
					<i class="m-menu__link-icon fas fa-chalkboard"></i>
					<span class="m-menu__link-text">Live Message</span>
				</a>
			</li>
			<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" m-menu-submenu-toggle="hover">
				<a href="{{route('logout')}}" class="m-menu__link m-menu__toggle">
					<i class="m-menu__link-icon fas fa-logout"></i>
					<span class="m-menu__link-text">Logout</span>
				</a>
			</li>
		</ul>
	</div>
</div>

resources/views/layouts/_partials/style.blade.php
<link href="/metronic_v5.1.1/metronic_v5.1.1/default/dist/default/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />		
<link href="/metronic_v5.1.1/metronic_v5.1.1/default/dist/default/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css" />
<link href="/css/custom.css" rel="stylesheet" type="text/css"/>
@yield('page_style')